"""Skeleton and code generation for new projects.

Step 0 follows the approved Code Profile.  The default remains the module-based CMake project whose
build scripts carry the toolchain logic proven on the sample project (Homebrew LLVM on macOS, a cache
from another checkout discarded).
"""

from __future__ import annotations

import re
from collections.abc import Mapping
from pathlib import Path

from icoda_core import persistence

CXX_STANDARD = "23"


def project_identifier(name: str) -> str:
    """A CMake/C++-safe identifier from a project name."""
    identifier = re.sub(r"[^A-Za-z0-9_]+", "_", name.strip()).strip("_") or "project"
    return identifier if not identifier[0].isdigit() else f"p_{identifier}"


def skeleton_files(name: str, code_profile: Mapping[str, object] | None = None) -> dict[str, str]:
    """Relative path -> content of the step 0 skeleton for a project called ``name``."""
    if code_profile is not None and code_profile.get("language") == "Python":
        return _python_skeleton_files(name, code_profile)
    ident = project_identifier(name)
    return {
        "CMakeLists.txt": _cmake_lists(ident),
        "CMakePresets.json": PRESETS,
        "build.sh": BUILD_SH,
        "build.cmd": BUILD_CMD,
        "vcpkg.json": _vcpkg_manifest(ident),
        "Doxyfile": _doxyfile(ident),
        ".gitignore": GITIGNORE,
        "README.md": _readme(name, ident),
        "examples/basic/main.cpp": MAIN_CPP,
        "src/app/app.cppm": APP_MODULE,
        "tests/smoke_test.cpp": SMOKE_TEST,
    }


def write_skeleton(
    root: Path, name: str, code_profile: Mapping[str, object] | None = None
) -> list[str]:
    """Write the skeleton under ``root`` (created if needed); existing files are left alone."""
    store = persistence.ProjectStore(root)
    had_state = store.state_path.exists()
    written = []
    for relative, content in skeleton_files(name, code_profile).items():
        target = root / relative
        if target.exists():
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        if relative.endswith(".sh"):
            target.chmod(0o755)
        written.append(relative)
    if written and not had_state:
        store.save_state(persistence.ProjectState(persistence.ProjectPhase.ARCHITECTURE))
    return written


def _python_skeleton_files(name: str, code_profile: Mapping[str, object]) -> dict[str, str]:
    module = _conventional_name(name, str(code_profile["module_naming"]))
    class_name = _conventional_name(name, str(code_profile["class_naming"]))
    function_convention = str(code_profile["function_naming"])
    run_name = _conventional_name("run", function_convention)
    main_name = _conventional_name("main", function_convention)
    test_name = _conventional_name(f"test {module} runs", function_convention)
    extension = str(code_profile["source_file_extension"])
    module_path = f"src/{module}{extension}"
    test_path = str(code_profile["test_file_convention"]).replace("<module>", module)
    framework = str(code_profile["test_framework"])
    runner = str(code_profile["test_runner"])
    return {
        ".gitignore": PYTHON_GITIGNORE,
        "README.md": _python_readme(name, module, framework, runner),
        "pyproject.toml": _python_pyproject(name),
        module_path: _python_module(class_name, run_name, main_name),
        test_path: _python_test(module, class_name, run_name, main_name, test_name, framework),
    }


def _conventional_name(value: str, convention: str) -> str:
    separated = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", value)
    words = re.findall(r"[A-Za-z0-9]+", separated) or ["project"]
    normalized = re.sub(r"[^a-z]", "", convention.lower())
    if normalized == "pascalcase":
        result = "".join(word[:1].upper() + word[1:].lower() for word in words)
    elif normalized == "camelcase":
        pascal = "".join(word[:1].upper() + word[1:].lower() for word in words)
        result = pascal[:1].lower() + pascal[1:]
    else:
        result = "_".join(word.lower() for word in words)
    return result if not result[0].isdigit() else f"p_{result}"


def _python_pyproject(name: str) -> str:
    package = project_identifier(name).lower().replace("_", "-")
    return f"""[project]
name = "{package}"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []
"""


def _python_readme(name: str, module: str, framework: str, runner: str) -> str:
    return f"""# {name}

Generated by ICODA as the step 0 Python skeleton. The initial `{module}` module is ready to grow one
architecture step at a time.

Tests use {framework}; run them with `{runner}`.
"""


def _python_module(class_name: str, run_name: str, main_name: str) -> str:
    return f'''"""Application skeleton generated by ICODA."""


class {class_name}:
    """Application service; grows one architecture step at a time."""

    def {run_name}(self) -> int:
        """Run the empty application successfully."""
        return 0


def {main_name}() -> int:
    """Run the application entry point."""
    return {class_name}().{run_name}()
'''


def _python_test(
    module: str,
    class_name: str,
    run_name: str,
    main_name: str,
    test_name: str,
    framework: str,
) -> str:
    return f'''"""{framework} smoke test for the generated application skeleton."""

from src.{module} import {class_name}, {main_name}


def {test_name}() -> None:
    """The application service and entry point return success."""
    assert {class_name}().{run_name}() == 0
    assert {main_name}() == 0
'''


def module_unit(module: str, brief: str, body: str = "") -> str:
    """A module interface unit with the standard library in the global module fragment."""
    return (f"module;\n#include <string>\n#include <vector>\nexport module {module};\n\n"
            f"/// @brief {brief}\n{body}")


def _cmake_lists(ident: str) -> str:
    return f"""cmake_minimum_required(VERSION 3.28)
if(DEFINED ENV{{VCPKG_ROOT}} AND NOT CMAKE_TOOLCHAIN_FILE AND EXISTS "$ENV{{VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake")
  set(CMAKE_TOOLCHAIN_FILE "$ENV{{VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "vcpkg toolchain")
endif()
project({ident} VERSION 0.1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD {CXX_STANDARD})
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${{CMAKE_SOURCE_DIR}}/bin/${{CMAKE_BUILD_TYPE}}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${{CMAKE_SOURCE_DIR}}/bin/${{CMAKE_BUILD_TYPE}}")

# One C++20 module per concept; the library holds everything except main().
add_library({ident}_lib STATIC)
target_sources({ident}_lib PUBLIC FILE_SET CXX_MODULES FILES
    src/app/app.cppm
)

add_executable({ident} examples/basic/main.cpp)
target_link_libraries({ident} PRIVATE {ident}_lib)

enable_testing()
add_executable(smoke_test tests/smoke_test.cpp)
target_link_libraries(smoke_test PRIVATE {ident}_lib)
add_test(NAME smoke COMMAND smoke_test)
"""


PRESETS = """{
  "version": 6,
  "cmakeMinimumRequired": { "major": 3, "minor": 28, "patch": 0 },
  "configurePresets": [
    {
      "name": "base",
      "hidden": true,
      "generator": "Ninja",
      "binaryDir": "${sourceDir}/build/${presetName}",
      "cacheVariables": { "CMAKE_EXPORT_COMPILE_COMMANDS": "ON" }
    },
    { "name": "debug", "inherits": "base", "cacheVariables": { "CMAKE_BUILD_TYPE": "Debug" } },
    { "name": "release", "inherits": "base", "cacheVariables": { "CMAKE_BUILD_TYPE": "Release" } }
  ],
  "buildPresets": [
    { "name": "debug", "configurePreset": "debug" },
    { "name": "release", "configurePreset": "release" }
  ],
  "testPresets": [
    { "name": "debug", "configurePreset": "debug", "output": { "outputOnFailure": true } },
    { "name": "release", "configurePreset": "release", "output": { "outputOnFailure": true } }
  ]
}
"""

BUILD_SH = """#!/usr/bin/env bash
# Configure/build and normally test one preset. Usage: ./build.sh [debug|release] [build-only]
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
preset="${1:-debug}"
mode="${2:-all}"
# A cache created from another checkout (or another machine) makes CMake refuse to configure; start fresh then.
cache="build/$preset/CMakeCache.txt"
if [ -f "$cache" ] && ! grep -qx "CMAKE_HOME_DIRECTORY:INTERNAL=$PWD" "$cache"; then
  echo "build.sh: build/$preset was configured for another source directory; removing it" >&2
  rm -rf "build/$preset"
fi
extra=()
if [ "$(uname -s)" = "Darwin" ] && [ -z "${CXX:-}" ]; then
  # CMake cannot build C++20 modules with Apple's clang (its AppleClang configuration has no module scanning),
  # so use Homebrew's LLVM when it is installed.
  llvm_prefix="$(brew --prefix llvm 2>/dev/null || true)"
  if [ -x "$llvm_prefix/bin/clang++" ]; then
    export CC="$llvm_prefix/bin/clang" CXX="$llvm_prefix/bin/clang++"
    echo "build.sh: using Homebrew LLVM at $llvm_prefix" >&2
  else
    echo "build.sh: Apple's clang cannot build C++20 modules with CMake; install LLVM with 'brew install llvm'" >&2
  fi
fi
cmake --preset "$preset" ${extra[@]+"${extra[@]}"}
cmake --build --preset "$preset"
if [ "$mode" != "build-only" ]; then
  ctest --preset "$preset"
fi
"""

BUILD_CMD = """@echo off
rem Configure/build and normally test one preset. Usage: build.cmd [debug|release] [build-only]
setlocal
cd /d "%~dp0"
set "PRESET=%~1"
if "%PRESET%"=="" set "PRESET=debug"
set "MODE=%~2"
if exist "build\\%PRESET%\\CMakeCache.txt" (
    findstr /x /c:"CMAKE_HOME_DIRECTORY:INTERNAL=%CD:\\=/%" "build\\%PRESET%\\CMakeCache.txt" >nul || (
        echo build.cmd: build\\%PRESET% was configured for another source directory; removing it 1>&2
        rmdir /s /q "build\\%PRESET%"
    )
)
if "%CXX%"=="" (
    where clang-cl >nul 2>nul && set "CC=clang-cl" && set "CXX=clang-cl"
)
cmake --preset %PRESET% || exit /b 1
cmake --build --preset %PRESET% || exit /b 1
if /i "%MODE%"=="build-only" exit /b 0
ctest --preset %PRESET% || exit /b 1
"""

GITIGNORE = """build/
bin/
vcpkg_installed/
.icoda/cache/
.icoda/ui.json
.icoda/icoda.log
docs/html/
.DS_Store
.vscode/
.idea/
"""

PYTHON_GITIGNORE = """__pycache__/
*.py[cod]
.pytest_cache/
.mypy_cache/
.ruff_cache/
.venv/
.icoda/cache/
.icoda/ui.json
.icoda/icoda.log
.DS_Store
.vscode/
.idea/
"""

MAIN_CPP = """/// @file main.cpp
/// @brief Basic example: hands over to the application module.
import app;

/// @brief Program entry.
int main() {
    return app::run();
}
"""

APP_MODULE = """module;
#include <string>
export module app;

/// @brief The application; grows one architecture step at a time.
export namespace app {

/// @brief Runs the application; empty until the first step fills it in.
int run() {
    return 0;
}

}  // namespace app
"""

SMOKE_TEST = """/// @brief Smoke test: the application runs and returns success.
import app;

int main() {
    return app::run() == 0 ? 0 : 1;
}
"""


def _vcpkg_manifest(ident: str) -> str:
    return f'{{\n  "name": "{ident.lower().replace("_", "-")}",\n  "version-string": "0.1.0",\n  "dependencies": []\n}}\n'


def _doxyfile(ident: str) -> str:
    return f"""PROJECT_NAME           = "{ident}"
INPUT                  = src
RECURSIVE              = YES
FILE_PATTERNS          = *.cpp *.cppm *.h *.hpp
EXTENSION_MAPPING      = cppm=C++
OUTPUT_DIRECTORY       = docs
GENERATE_LATEX         = NO
EXTRACT_ALL            = YES
QUIET                  = YES
ALIASES                = "satisfies=\\\\par Satisfies:^^"
"""


def _readme(name: str, ident: str) -> str:
    return f"""# {name}

Generated by ICODA as the step 0 skeleton: a C++{CXX_STANDARD} project built from C++20 modules with CMake presets.

Build and test with `./build.sh` (macOS, Linux) or `build.cmd` (Windows); binaries land in `bin/<config>/`,
build artefacts in `build/<preset>/`. Libraries are declared in `vcpkg.json`; set `VCPKG_ROOT` to use them.
The target `{ident}` runs `examples/basic/main.cpp`, which links the `{ident}_lib` module library in `src/`.
Keep example and demo sources in `examples/`; use a subdirectory for each multi-file example.
The `smoke_test` target runs through CTest.
"""
