"""Generate the opt-in C/C++ call-recording runtime and its CMake injection.

The generated runtime uses Clang/GCC ``-finstrument-functions`` hooks.  It writes
the versioned format documented by :mod:`icoda_core.call_trace`, stops after the
configured interval, and permanently disables itself if the trace cannot be
opened or written.  Generated sources and the isolated instrumented build tree
live below the target project's ignored ``.icoda/cache`` directory.
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from pathlib import Path

from icoda_core.persistence import ICODA_DIR

DEFAULT_DURATION_SECONDS = 5.0
DEFAULT_TRACE_NAME = "call-trace.tsv"


@dataclass(frozen=True)
class InstrumentationOptions:
    """Configuration for an instrumented debug build; disabled by default."""

    enabled: bool = False
    duration_seconds: float = DEFAULT_DURATION_SECONDS
    trace_file: Path | None = None


@dataclass(frozen=True)
class InstrumentationFiles:
    """Generated inputs and CMake arguments for one instrumented build."""

    runtime_source: Path
    cmake_include: Path
    build_directory: Path
    trace_file: Path
    cmake_arguments: tuple[str, ...]


def prepare_instrumentation(root: Path, options: InstrumentationOptions) -> InstrumentationFiles:
    """Generate the runtime and return flags for an isolated CMake configuration."""
    if not options.enabled:
        raise ValueError("call instrumentation must be explicitly enabled")
    if not math.isfinite(options.duration_seconds) or options.duration_seconds <= 0:
        raise ValueError("call instrumentation duration_seconds must be a positive finite number")

    root = root.resolve()
    generated = root / ICODA_DIR / "cache" / "call-instrumentation"
    generated.mkdir(parents=True, exist_ok=True)
    trace_file = options.trace_file or root / ICODA_DIR / "cache" / DEFAULT_TRACE_NAME
    if not trace_file.is_absolute():
        trace_file = root / trace_file
    trace_file = trace_file.resolve()
    runtime_source = generated / "runtime.cpp"
    cmake_include = generated / "instrumentation.cmake"
    _write_if_changed(runtime_source, _runtime_source(trace_file, options.duration_seconds))
    _write_if_changed(cmake_include, _cmake_source(runtime_source))
    return InstrumentationFiles(
        runtime_source,
        cmake_include,
        root / ICODA_DIR / "cache" / "instrumented-debug-build",
        trace_file,
        ("-DICODA_CALL_TRACE_ENABLED=ON", f"-DCMAKE_PROJECT_INCLUDE={cmake_include.as_posix()}"),
    )


def _write_if_changed(path: Path, contents: str) -> None:
    if path.is_file() and path.read_text(encoding="utf-8") == contents:
        return
    path.write_text(contents, encoding="utf-8")


def _cmake_source(runtime_source: Path) -> str:
    source = runtime_source.as_posix().replace('"', '\\"')
    return f'''# Generated by ICODA. Changes are replaced by the next instrumented build.
if(ICODA_CALL_TRACE_ENABLED AND NOT TARGET icoda_call_trace_runtime)
  add_library(icoda_call_trace_runtime SHARED "{source}")
  set_target_properties(icoda_call_trace_runtime PROPERTIES
    POSITION_INDEPENDENT_CODE ON)
  if(CMAKE_DL_LIBS)
    target_link_libraries(icoda_call_trace_runtime PRIVATE "${{CMAKE_DL_LIBS}}")
  endif()
  add_compile_options(-finstrument-functions)
  if(NOT WIN32)
    add_link_options(-rdynamic)
  endif()
  link_libraries(icoda_call_trace_runtime)
endif()
'''


def _runtime_source(trace_file: Path, duration_seconds: float) -> str:
    trace_literal = json.dumps(str(trace_file), ensure_ascii=False)
    duration_ns = round(duration_seconds * 1_000_000_000)
    return f'''// Generated by ICODA. Changes are replaced by the next instrumented build.
#if defined(__linux__) && !defined(_GNU_SOURCE)
#  define _GNU_SOURCE
#endif
#include <cinttypes>
#include <cstdint>
#include <cstdio>

#if defined(_WIN32)
#  define WIN32_LEAN_AND_MEAN
#  include <windows.h>
#else
#  include <dlfcn.h>
#  include <time.h>
#endif

#if defined(__clang__) || defined(__GNUC__)
#  define ICODA_NOINSTRUMENT __attribute__((no_instrument_function))
#  define ICODA_CONSTRUCTOR __attribute__((constructor(101)))
#  define ICODA_EXPORT __attribute__((visibility("default")))
#else
#  define ICODA_NOINSTRUMENT
#  define ICODA_CONSTRUCTOR
#  define ICODA_EXPORT
#endif
#if defined(_WIN32)
#  undef ICODA_EXPORT
#  define ICODA_EXPORT __declspec(dllexport)
#endif

static const char *const trace_path = {trace_literal};
static const std::uint64_t trace_duration_ns = UINT64_C({duration_ns});
static std::FILE *trace_output = nullptr;
static std::uint64_t trace_start_ns = 0;
static int trace_state = 0;  // 0 uninitialised, 1 initialising, 2 recording, -1 unavailable, 3 expired
static thread_local unsigned trace_depth = 0;
static thread_local bool trace_guard = false;
#if defined(_WIN32)
static std::uint64_t performance_frequency = 0;
#endif

static std::uint64_t monotonic_ns() ICODA_NOINSTRUMENT;
static std::uint64_t monotonic_ns() {{
#if defined(_WIN32)
    LARGE_INTEGER counter;
    if (!performance_frequency || !QueryPerformanceCounter(&counter)) return 0;
    return static_cast<std::uint64_t>(counter.QuadPart) * UINT64_C(1000000000) / performance_frequency;
#else
    struct timespec value {{}};
    if (clock_gettime(CLOCK_MONOTONIC, &value) != 0) return 0;
    return static_cast<std::uint64_t>(value.tv_sec) * UINT64_C(1000000000)
        + static_cast<std::uint64_t>(value.tv_nsec);
#endif
}}

static void initialise_trace() ICODA_NOINSTRUMENT;
static void initialise_trace() {{
    int expected = 0;
    if (!__atomic_compare_exchange_n(&trace_state, &expected, 1, false,
                                     __ATOMIC_ACQ_REL, __ATOMIC_ACQUIRE)) return;
#if defined(_WIN32)
    LARGE_INTEGER frequency;
    if (QueryPerformanceFrequency(&frequency))
        performance_frequency = static_cast<std::uint64_t>(frequency.QuadPart);
#endif
    trace_start_ns = monotonic_ns();
    trace_output = std::fopen(trace_path, "w");
    if (!trace_output) {{
        __atomic_store_n(&trace_state, -1, __ATOMIC_RELEASE);
        return;
    }}
    // Buffered modes require a nonzero size in the Windows CRT.
    std::setvbuf(trace_output, nullptr, _IOLBF, BUFSIZ);
    if (std::fprintf(trace_output,
            "# icoda-call-trace-v1\\n"
            "# columns=event\\ttimestamp_ns\\tthread\\tdepth\\tfunction\\tcaller\\tsymbol\\tmodule\\n") < 0) {{
        std::fclose(trace_output);
        trace_output = nullptr;
        __atomic_store_n(&trace_state, -1, __ATOMIC_RELEASE);
        return;
    }}
    __atomic_store_n(&trace_state, 2, __ATOMIC_RELEASE);
}}

static void constructor_initialise_trace() ICODA_NOINSTRUMENT ICODA_CONSTRUCTOR;
static void constructor_initialise_trace() {{ initialise_trace(); }}

static void lock_trace() ICODA_NOINSTRUMENT;
static void lock_trace() {{
#if defined(_WIN32)
    _lock_file(trace_output);
#else
    flockfile(trace_output);
#endif
}}

static void unlock_trace() ICODA_NOINSTRUMENT;
static void unlock_trace() {{
#if defined(_WIN32)
    _unlock_file(trace_output);
#else
    funlockfile(trace_output);
#endif
}}

struct FunctionInfo {{
    std::uintptr_t address;
    const char *symbol;
    const char *module;
#if defined(_WIN32)
    char module_buffer[MAX_PATH];
#endif
}};

static FunctionInfo function_info(void *function) ICODA_NOINSTRUMENT;
static FunctionInfo function_info(void *function) {{
    FunctionInfo result {{reinterpret_cast<std::uintptr_t>(function), "", ""
#if defined(_WIN32)
        , {{}}
#endif
    }};
#if defined(_WIN32)
    HMODULE module = nullptr;
    if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS
                          | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                          reinterpret_cast<LPCSTR>(function), &module)) {{
        if (GetModuleFileNameA(module, result.module_buffer, MAX_PATH)) result.module = result.module_buffer;
        result.address -= reinterpret_cast<std::uintptr_t>(module);
    }}
#else
    Dl_info details {{}};
    if (dladdr(function, &details) && details.dli_fbase) {{
        result.address -= reinterpret_cast<std::uintptr_t>(details.dli_fbase);
        result.symbol = details.dli_sname ? details.dli_sname : "";
        result.module = details.dli_fname ? details.dli_fname : "";
    }}
#endif
    return result;
}}

static void write_field(const char *value) ICODA_NOINSTRUMENT;
static void write_field(const char *value) {{
    for (; value && *value; ++value)
        std::fputc(*value == '\\t' || *value == '\\n' || *value == '\\r' ? ' ' : *value, trace_output);
}}

static void record_event(char event, void *function, void *caller, unsigned depth) ICODA_NOINSTRUMENT;
static void record_event(char event, void *function, void *caller, unsigned depth) {{
    if (__atomic_load_n(&trace_state, __ATOMIC_ACQUIRE) == 0) initialise_trace();
    if (__atomic_load_n(&trace_state, __ATOMIC_ACQUIRE) != 2 || !trace_output) return;
    lock_trace();
    if (__atomic_load_n(&trace_state, __ATOMIC_RELAXED) != 2) {{ unlock_trace(); return; }}
    const std::uint64_t now = monotonic_ns();
    const std::uint64_t elapsed = now >= trace_start_ns ? now - trace_start_ns : 0;
    if (elapsed > trace_duration_ns) {{
        std::fflush(trace_output);
        __atomic_store_n(&trace_state, 3, __ATOMIC_RELEASE);
        unlock_trace();
        return;
    }}
    const FunctionInfo info = function_info(function);
    const std::uintptr_t thread = reinterpret_cast<std::uintptr_t>(&trace_depth);
    std::fprintf(trace_output, "%c\\t%" PRIu64 "\\t0x%" PRIxPTR "\\t%u\\t0x%" PRIxPTR
                 "\\t0x%" PRIxPTR "\\t", event, elapsed, thread, depth, info.address,
                 reinterpret_cast<std::uintptr_t>(caller));
    write_field(info.symbol);
    std::fputc('\\t', trace_output);
    write_field(info.module);
    std::fputc('\\n', trace_output);
    if (std::ferror(trace_output)) __atomic_store_n(&trace_state, -1, __ATOMIC_RELEASE);
    unlock_trace();
}}

extern "C" ICODA_EXPORT void __cyg_profile_func_enter(void *function, void *caller)
    ICODA_NOINSTRUMENT;
extern "C" ICODA_EXPORT void __cyg_profile_func_enter(void *function, void *caller) {{
    if (trace_guard) return;
    trace_guard = true;
    record_event('E', function, caller, trace_depth);
    ++trace_depth;
    trace_guard = false;
}}

extern "C" ICODA_EXPORT void __cyg_profile_func_exit(void *function, void *caller)
    ICODA_NOINSTRUMENT;
extern "C" ICODA_EXPORT void __cyg_profile_func_exit(void *function, void *caller) {{
    if (trace_guard) return;
    trace_guard = true;
    if (trace_depth) --trace_depth;
    record_event('X', function, caller, trace_depth);
    trace_guard = false;
}}
'''
